# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"G01D3PMFPU2\",\"attachments\": [{\"fallback\": \"Required plain-text summary of the attachment.\",\"color\": \"#36a64f\",\"author_link\": \"http://flickr.com/bobby/\",\"author_icon\": \"http://flickr.com/icons/bobby.jpg\",\"title\": \"Github Pull Request\",\"title_link\": \"https://github.com/jainahik/new/pull/25\",\"text\": \"Pull Request has been raised\",\"image_url\": \"http://my-website.com/path/to/image.jpg\",\"thumb_url\": \"http://example.com/path/to/thumb.png\"}]}'
